name: Feature request
description: Suggest an improvement for the public client.
title: "feature: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
